services:
  - docker:dind

stages:
  - publish-gh

publish-gh:
  image: ubuntu
  stage: publish-gh
  only:
    - master
  script:
    - apt update
    - apt install -y --no-install-recommends git openssh-client
    - mkdir -p ~/.ssh
    - echo "$GH_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa" git push -f git@github.com:swarmfund/swarm-js-base.git master
